services:
  - type: web
    name: kandala-ultra-pair
    env: node
    buildCommand: corepack enable && corepack prepare npm@9.8.0 --activate && npm install --no-audit --prefer-offline --no-fund
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NODE_VERSION
        value: "18.20.0"
      - key: BOT_NAME
        value: "KANDALA CONNECT"
    autoDeploy: true
