services:
    - type: web
    name: kandala-ultra-pair
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
            - key: NODE_ENV
        value: production
            - key: PORT
        value: 3000
            - key: NODE_VERSION
        value: 18.20.0
            - key: BOT_NAME
        value: KANDALA CONNECT
    autoDeploy: true
